server:
  port: 9007
spring:
  application:
    name: micro-eureka

eureka:
  client:
    registerWithEureka: false #不注册
    fetchRegistry: false #不检索
    service-url:
      defaultZone: http://localhost:9007/eureka
#eureka