server:
    port: 9349

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/miao?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
        username: root
        password: 123456
    thymeleaf:
        cache: true
    redis:
        database: 2
        host: localhost
        port: 6379
    rabbitmq:
        host: 192.168.105.59
        port: 5672
        virtual-host: /
        username: mq
        password: 1234
    application:
         name: micro-miao-killorder
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9007/eureka
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        type-aliases-package: com.model